### ISSUE TITLE
Only 885 posts listed, though there are many more

### ISSUE THREAD

**Issue by Rustlingsoul** [aplotor/expanse#46]
Please forgive me, I'm not the most tech savvy, but I got expanse running and noticed that there are a fair bit of posts missing. Expanse lists 885 posts saved (and syncs any new ones added) but is missing years of older content, even if I update it through Git Bash.

Is there something that I'm doing wrong?

Thanks!

**Comment by aplotor** [comment]
to get your full history into expanse, use the import feature in the cog at the top right of the page

also, the updating instructions in the README are for updating the application itself, not for updating reddit data within expanse

**Comment by Rustlingsoul** [comment]
Thank you for the prompt reply!
